image: node:alpine

before_script:
  - apk add --no-cache rsync

pages:
  script:
    - mkdir public
    - rsync -av --exclude=public ./ public/
  artifacts:
    paths:
      - public
  only:
    - main
